# permissions for end users to edit yttsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yttsource-editor-role
rules:
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - yttsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - yttsources/status
  verbs:
  - get
