# permissions for end users to view yttsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yttsource-viewer-role
rules:
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - yttsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extension.projectsveltos.io
  resources:
  - yttsources/status
  verbs:
  - get
